/**
 * Created by Ps on 2017/1/17.
 */
var world,wo,we,fixDef=new b2FixtureDef,bodyDef=new b2BodyDef,drawScale=30,canvaswidth=1E3,canvasheight=600,backgroundcolor="#FFFFFF",defaultfont="Hobo Std",colorthemenum=0,bodyList=[],ifattract=[],tagColor=[],tagFont=[],drawnBody=[],bodywidth=[],bodyheight=[],prePosition=[],wordsNeighbor=[],PreNeighbor=[],preReWordleReason=[-1,-1],constrainBody=[],fw=[0,0,0,0,0,Math.PI/2,-Math.PI/2],color=["#97ADAC #AD8976 #FF9680 #002228 #FF5E48 #f0a262".split(" "),"#295AA6 #51BDBD #f0a262 #e47b9c #ceb55b #2eafcf".split(" "),
    "#c92b28 #e88c59 #f3d501 #d59534 #2aaec7 #6a7caa".split(" "),"#504b2e #a8be40 #8bc27e #c5ddd0 #c1d63d #7faf35".split(" ")],planet=[],iternum=9E3,limit=200,isFirstContrust=!0,ifstart=!1,ifedit=!1,ifaddconstrain=!1,rayFixture,wordsiternum,context,radiusRatio=.8,startPositionRatio=.5,Reflag=!0,Ifdebug=!1,usecenter=!0,ifAllFixed=!0,maxfontsize=56,minfontsize=15;function init(){createWorld();createWall();debugDraw();createObject();window.setInterval(update,1E3/60)}
function SetWordsAndWeight(a,b){wo=a;we=b}function getText(){var a=window.location.href.split("?"),b=a[1].split("=")[1],b=decodeURI(b),b=eval("("+b+")");wo=b.wolistall[0];we=b.welistall[0];if(a[2])for(b=a[2].split("=")[1],b=decodeURI(b),a=eval("("+b+")"),b=0;b<a.length;b++){for(var c=[],e=0;e<a[b].length;e++)for(var d=0;d<wo.length;d++)a[b][e]==wo[d]&&(c[e]=d);constrainBody[b]=c}}function createWorld(){world=new b2World(new b2Vec2(0,0),!0);world.SetWarmStarting(!1)}
function createWall(){fixDef.density=1;fixDef.friction=.5;fixDef.restitution=.2;bodyDef.type=b2Body.b2_staticBody;fixDef.shape=new b2PolygonShape;fixDef.shape.SetAsBox(canvaswidth/30,2);bodyDef.position.Set(canvaswidth/30/2,canvasheight/30+1.8);world.CreateBody(bodyDef).CreateFixture(fixDef);bodyDef.position.Set(canvaswidth/30/2,-1.8);world.CreateBody(bodyDef).CreateFixture(fixDef);fixDef.shape.SetAsBox(2,canvasheight/30);bodyDef.position.Set(-1.8,canvasheight/30);world.CreateBody(bodyDef).CreateFixture(fixDef);
    bodyDef.position.Set(canvaswidth/30+1.8,canvasheight/30);world.CreateBody(bodyDef).CreateFixture(fixDef);bodyDef.type=b2Body.b2_staticBody;fixDef.shape=new b2CircleShape(.01/drawScale);bodyDef.position.Set(canvaswidth/drawScale/2,canvasheight/drawScale/2);var a=world.CreateBody(bodyDef);fixDef.isSensor=!0;a.CreateFixture(fixDef);planet.push(a)}
function createObject(){for(var a=0;a<we.length;a++){var b,c;b=createOffSet();c=createOffSet();createBox(canvaswidth/2+4*b,canvasheight/2+1.5*c,we[a],a,!0,void 0,void 0,void 0,!1)}iternum=0}
function createBox(a,b,c,e,d,f,h,g,m){tagFont[e]=d?defaultfont:g;fixDef.isSensor=!1;fixDef.density=1;fixDef.friction=.2;bodyDef.type=b2Body.b2_dynamicBody;fixDef.shape=new b2PolygonShape;g=(maxfontsize-minfontsize)*c+minfontsize;var k=wo[e].visualLength(g,tagFont[e]);fixDef.shape.SetAsBox(k/drawScale/2,g/drawScale/2/1.1);bodyDef.position.Set(a/drawScale,b/drawScale);a=world.CreateBody(bodyDef);a.CreateFixture(fixDef);a.SetID(e);bodyList[e]=a;bodywidth[e]=k/2;bodyheight[e]=g/2;d?(tagColor[e]=createColor(),
.7>=c&&a.SetAngle(createAngle())):(tagColor[e]=f,a.SetAngle(h));ifattract[e]=!0;a.SetFixedRotation(ifAllFixed);if(a.IsFixedRotation()){for(c=a.GetFixtureList();c;c=c.m_next)c.SetSensor(!0);c=placeBody(a,m);m&&PickPosition(c,a);for(c=a.GetFixtureList();c;c=c.m_next)c.SetSensor(!1)}}
function preserveConstrain(){for(var a=0;a<constrainBody.length;a++){for(var b=[],c=0;c<a;c++)for(var e=0;e<constrainBody[c].length;e++)b.push(constrainBody[c][e]);if(0<=constrainBody[a][0]){constrainBody[a].sort(sortNumber);for(var c=constrainBody[a][0],e=findNeighbor(!0,c),d=1;d<constrainBody[a].length;d++){for(var f=constrainBody[a][d],h=999,g=-1,m=!1,k=.1;-1==g;){for(var l=0;l<e.length;l++)if(f==e[l]&&(m=!0),-1==b.indexOf(e[l])&&Math.abs(we[f]-we[e[l]])<k){var n=!0;bodyList[f].IsFixedRotation()&&
0!=bodyList[e[l]].GetAngle()&&(n=!1);n&&(n=Math.abs(bodywidth[f]-bodywidth[e[l]]),n<h&&(h=n,g=e[l]))}k+=.1}m||changeBodyPosition(f,g);tagColor[f]=tagColor[c]}}}}
function changeBodyPosition(a,b){var c=bodyList[a],e=bodyList[b];c.IsFixedRotation()&&0!=c.GetAngle()&&(e.SetAngle(c.GetAngle()),c.SetAngle(0));for(var d=c.GetFixtureList();d;d=d.m_next)d.SetSensor(!0);for(d=e.GetFixtureList();d;d=d.m_next)d.SetSensor(!0);var d=c.GetPosition().x,f=c.GetPosition().y,h=e.GetPosition().x,g=e.GetPosition().y;c.SetPosition(new b2Vec2(h,g));e.SetPosition(new b2Vec2(d,f));for(d=c.GetFixtureList();d;d=d.m_next)d.SetSensor(!1);for(d=e.GetFixtureList();d;d=d.m_next)d.SetSensor(!1)}
function createOffSet(){return.5<=Math.random()?70*Math.random():70*-Math.random()}
function placeBody(a,b){var c=0,e=[],d=null,f=600;b&&(f=1E3);for(var h=0;h<f;h++){var g=getSpiralNudger(h),m=a.GetPosition().x+g.x/drawScale/2,g=a.GetPosition().y+g.y/drawScale/2;a.SetPosition(new b2Vec2(m,g));var k=a.GetPosition();if(!(0>k.x||0>k.y||k.x>canvaswidth||k.y>canvasheight||null!=d&&isOverlap(d,a,b))){for(var k=!1,l=0;l<drawnBody.length;l++)if(isOverlap(drawnBody[l],a,b)){k=!0;d=drawnBody[l];break}if(!k)if(b)if(20>c)e[c]={x:m,y:g},c++;else return e;else return drawnBody.push(a),!0;a.GetID()}}return b?
    e:!1}function isOverlap(a,b,c){var e=a.GetPosition(),d=b.GetPosition(),f=a.GetID(),h=b.GetID();a=0!=a.GetAngle();b=0!=b.GetAngle();e=getPoint(e,f,a,c);c=getPoint(d,h,b,c);return!(e[3]<=c[1]||e[1]>=c[3]||e[2]<=c[0]||e[0]>=c[2])}
function getPoint(a,b,c,e){var d=[],f=1;e&&(f=.9);c?(d[0]=a.x*drawScale-bodyheight[b]*f,d[1]=a.y*drawScale-bodywidth[b]*f,d[2]=a.x*drawScale+bodyheight[b]*f,d[3]=a.y*drawScale+bodywidth[b]*f):(d[0]=a.x*drawScale-bodywidth[b]*f,d[1]=a.y*drawScale-bodyheight[b]*f,d[2]=a.x*drawScale+bodywidth[b]*f,d[3]=a.y*drawScale+bodyheight[b]*f);return d}function getSpiralNudger(a){var b=powerMap(.5,a,0,600,1,100);a*=powerMap(1,a,0,600,.5,.3);return new b2Vec2(Math.cos(a)*b,Math.sin(a)*b)}
function powerMap(a,b,c,e,d,f){return(f-d)*Math.pow(b/(e-c),a)+d}function debugDraw(){var a=new b2DebugDraw;context=document.getElementById("canvas").getContext("2d");a.SetSprite(context);a.SetDrawScale(30);a.SetFillAlpha(.5);a.SetLineThickness(1);a.SetFlags(b2DebugDraw.e_shapeBit|b2DebugDraw.e_jointBit);world.SetDebugDraw(a)}
var mouseX,mouseY,premouseX=void 0,premouseY=void 0,mousePVec,isMouseMove,isMouseRotate,selectedBody,hasselect={flag:!1,time:0},preselectBody,mrRadian,firstrotate=!0,scalestart,scaleend,rotationstart,rotationend,startposition=void 0,prefingerpositon=[],canvasPosition=getElementPosition(document.getElementById("canvas")),canvas=document.getElementById("canvas");canvas.addEventListener("mousedown",handleMouseDown,!0);canvas.addEventListener("touchstart",handleMouseDown,!0);
canvas.addEventListener("mouseup",handleMouseUp,!0);canvas.addEventListener("touchend",handleMouseUp,!0);canvas.addEventListener("mousewheel",handleMousescroll,!0);var mc=new Hammer.Manager(canvas),pinch=new Hammer.Pinch,rotate=new Hammer.Rotate;pinch.recognizeWith(rotate);mc.add([pinch,rotate]);mc.on("rotatestart rotatemove",handleTouchRotate);mc.on("pinchstart pinchmove",handleTouchPinch);
function handleMouseDown(a){var b,c;if(a.clientX)b=a.clientX,c=a.clientY;else if(a.changedTouches&&0<a.targetTouches.length&&1==a.targetTouches.length)c=a.changedTouches[a.changedTouches.length-1],b=c.clientX,c=c.clientY;else return;canvasPosition=getElementPosition(document.getElementById("canvas"));mouseX=(b-canvasPosition.x)/30;mouseY=(c-canvasPosition.y)/30;premouseX=mouseX;premouseY=mouseY;a.preventDefault();if(hasselect.flag&&1<=hasselect.time)if(b=getBodyAtMouse())if(ifaddconstrain){a=constrainBody.length-
    1;b=b.GetID();c=!1;for(var e=0;e<constrainBody[a].length;e++)constrainBody[a][e]==b&&(constrainBody[a].remove(b),c=!0);c||constrainBody[a].push(b)}else preselectBody==b?(hasselect.time++,ifaddconstrain||(handleMouseMove(a),canvas.addEventListener("mousemove",handleMouseMove,!0),canvas.addEventListener("touchmove",handleMouseMove,!0))):(preselectBody=b,document.getElementById("wordfont").value=tagFont[b.GetID()],document.getElementById("wordColor").jscolor.fromString(tagColor[b.GetID()].substr(1)),
    document.getElementById("wordColor").value="word color",ifedit=hasselect.flag=!0,hasselect.time=1,handleMouseMove(a),canvas.addEventListener("mousemove",handleMouseMove,!0),canvas.addEventListener("touchmove",handleMouseMove,!0));else ifaddconstrain||(handleMouseUp(),hasselect.flag=!1,hasselect.time=0),startposition=premouseY=premouseX=mouseY=mouseX=void 0,firstrotate=!0,mrRadian=selectedBody=preselectBody=void 0,document.getElementById("wordedittools").style.display="none";else if(b=getBodyAtMouse())hasselect.flag=
    !0,preselectBody=b,hasselect.time++,ifaddconstrain?(a=constrainBody.length,b=b.GetID(),c=[],c.push(b),constrainBody[a]=c):(ifedit=!0,document.getElementById("wordedittools").style.display="",document.getElementById("wordfont").value=tagFont[b.GetID()],document.getElementById("wordColor").jscolor.fromString(tagColor[b.GetID()].substr(1)),document.getElementById("wordColor").value="word color",handleMouseMove(a),canvas.addEventListener("mousemove",handleMouseMove,!0),canvas.addEventListener("touchmove",
    handleMouseMove,!0))}function handleMouseUp(){if(hasselect.flag){canvas.removeEventListener("mousemove",handleMouseMove,!0);canvas.removeEventListener("touchmove",handleMouseMove,!0);isMouseRotate=isMouseMove=!1;var a,b=preselectBody.GetID(i);for(a=preselectBody.GetFixtureList();a;a=a.m_next)a.SetSensor(!1);a=preselectBody.GetID();ifHorizontal(a);a=preselectBody.GetContactList();for(ifattract[b]=!1;a;){if(48==a.contact.m_flags){ifattract[b]=!0;break}a=a.next}}}
function handleMouseMove(a){var b,c;if(a.clientX)b=a.clientX,c=a.clientY;else if(a.changedTouches&&0<a.changedTouches.length)c=a.changedTouches[a.changedTouches.length-1],b=c.clientX,c=c.clientY;else return;canvasPosition=getElementPosition(document.getElementById("canvas"));mouseX=(b-canvasPosition.x)/30;mouseY=(c-canvasPosition.y)/30;a.preventDefault();preselectBody.SetAwake(!0);preselectBody.SetAngularVelocity(0);preselectBody.SetLinearVelocity(new b2Vec2(0,0));if(!(mouseX>=premouseX-2/30&&mouseX<=
    premouseX+2/30&&mouseY>=premouseY-2/30&&mouseY<=premouseY+2/30))for(b=preselectBody.GetFixtureList();b;b=b.m_next)b.SetSensor(!0);premouseX=mouseX;premouseY=mouseY;if(a.targetTouches){if(1==a.targetTouches.length&&hasselect.flag&&(isMouseMove=!0),2==a.targetTouches.length&&hasselect.flag)for(b=preselectBody.GetFixtureList();b;b=b.m_next)b.SetSensor(!1)}else if(0==a.button&&hasselect.flag&&(isMouseMove=!0),2==a.button&&hasselect.flag){for(b=preselectBody.GetFixtureList();b;b=b.m_next)b.SetSensor(!1);
    isMouseRotate=!0}iternum=0}
function handleMousescroll(a){a=a||window.event;if(hasselect.flag&&a.wheelDelta){if(0>a.wheelDelta){var b=selectedBody.GetID(),c=.9*we[b],e=((maxfontsize-minfontsize)*c+minfontsize)/2,d=e/bodyheight[b],f=selectedBody.GetFixtureList().GetShape(),f=f.GetVertices(),h;for(h in f){var g=f[h];g.x*=d;g.y*=d}}else for(h in b=selectedBody.GetID(),c=1.1*we[b],e=((maxfontsize-minfontsize)*c+minfontsize)/2,d=e/bodyheight[b],f=selectedBody.GetFixtureList().GetShape(),f=f.GetVertices(),f)g=f[h],g.x*=d,g.y*=d;bodyheight[b]=
    e;bodywidth[b]*=d;we[b]=c}a.preventDefault&&a.preventDefault();iternum=0}
function handleTouchRotate(a){if(hasselect.flag){isMouseRotate=isMouseMove=!1;var b;for(b=selectedBody.GetFixtureList();b;b=b.m_next)b.SetSensor(!1);switch(a.type){case "rotatestart":rotationstart=a.rotation;break;case "rotatemove":rotationend=a.rotation-rotationstart,rotationstart=a.rotation,selectedBody.SetAngularVelocity(0),selectedBody.SetLinearVelocity(new b2Vec2(0,0)),selectedBody.SetAwake(!0),selectedBody.m_force.SetZero(),b=selectedBody.GetAngle(),selectedBody.SetAngle(b+rotationend*Math.PI/
    180),prefingerpositon[0]={x:a.pointers[0].pageX,y:a.pointers[0].pageY},prefingerpositon[1]={x:a.pointers[1].pageX,y:a.pointers[1].pageY}}}}
function handleTouchPinch(a){if(hasselect.flag){var b=a.pointers,c=1;isMouseRotate=isMouseMove=!1;var e;for(e=selectedBody.GetFixtureList();e;e=e.m_next)e.SetSensor(!1);switch(a.type){case "pinchstart":scalestart=Math.sqrt((b[0].pageX-b[1].pageX)*(b[0].pageX-b[1].pageX)+(b[0].pageY-b[1].pageY)*(b[0].pageY-b[1].pageY));break;case "pinchmove":scaleend=Math.sqrt((b[0].pageX-b[1].pageX)*(b[0].pageX-b[1].pageX)+(b[0].pageY-b[1].pageY)*(b[0].pageY-b[1].pageY)),c=scaleend/scalestart,scalestart=scaleend}a=
    selectedBody.GetID();c*=we[a];b=((maxfontsize-minfontsize)*c+minfontsize)/2;e=b/bodyheight[a];var d=selectedBody.GetFixtureList().GetShape().GetVertices(),f;for(f in d){var h=d[f];h.x*=e;h.y*=e}bodyheight[a]=b;bodywidth[a]*=e;we[a]=c}}function getBodyAtMouse(){mousePVec=new b2Vec2(mouseX,mouseY);var a=new b2AABB;a.lowerBound.Set(mouseX-.001,mouseY-.001);a.upperBound.Set(mouseX+.001,mouseY+.001);selectedBody=null;world.QueryAABB(getBodyCB,a);return selectedBody}
function getBodyCB(a){return 0<=a.GetBody().GetID()&&a.GetShape().TestPoint(a.GetBody().GetTransform(),mousePVec)?(selectedBody=a.GetBody(),iternum=0,!1):!0}var tempPoint=new b2Vec2;
function findNeighbor(a,b){var c=0;a&&(c=b);for(c;c<bodyList.length;c++){var e;e=a?bodyList[c].GetPosition():prePosition[c];for(var d=[],f=0;f<bodyList.length;f++)if(f!=c){tempPoint=a?bodyList[f].GetPosition():prePosition[f];world.RayCast(callBack,e,tempPoint);var h=-1;rayFixture&&(h=rayFixture.GetBody().GetID());h==f&&d.push(f)}if(a)return d;wordsNeighbor[c]=d}}function callBack(a,b,c,e){rayFixture=a;return e}
function calR(a){for(var b=[[0,0],[0,0]],c=0;c<wordsNeighbor[a].length;c++)var e=wordsNeighbor[a][c],d=[[prePosition[a].x-prePosition[e].x],[prePosition[a].y-prePosition[e].y]],f=bodyList[a].GetPosition(),e=bodyList[e].GetPosition(),f=[[f.x-e.x],[f.y-e.y]],d=numeric.dot(d,numeric.transpose(f)),e=50*we[a]*we[c],e=e/(f[0][0]*f[0][0]+f[1][0]*f[1][0]),d=numeric.mul(d,e),b=numeric.add(b,d);for(d=0;2>d;d++)for(f=0;2>f;f++)b[d][f]=parseFloat(b[d][f].toFixed(4));d=numeric.svd(b);c=numeric.transpose(d.U);
    f=d.V;e=d.S;c=numeric.dot(f,c);0>=numeric.det(c)&&(c=numeric.dot(f,numeric.transpose(e[0]>e[1]?[[d.U[0][0],-d.U[0][1]],[d.U[1][0],-d.U[1][1]]]:[[-d.U[0][0],d.U[0][1]],[-d.U[1][0],d.U[1][1]]])));0>=numeric.det(c)&&console.log("\u53d1\u751f\u884c\u5217\u5f0f\u9519\u8bef\uff1a"+a);for(d=0;2>d;d++)for(f=0;2>f;f++)if(!c[d][f]&&0!=c[d][f])return console.log("R\u6709\u95ee\u9898"+JSON.stringify(b)),[[1,0],[0,1]];return c}
function calattractF(a){for(var b=[0,0],c=0;c<wordsNeighbor[a].length;c++){var e=bodyList[a].GetPosition(),d=wordsNeighbor[a][c],f=bodyList[d].GetPosition(),h=calR(a),g=calR(d),h=numeric.add(h,g),e=[[e.x-f.x],[e.y-f.y]],d=numeric.dot(h,[[prePosition[a].x-prePosition[d].x],[prePosition[a].y-prePosition[d].y]]),d=numeric.mul(d,-.5),d=numeric.add(e,d),d=numeric.mul(d,4E15),d=numeric.transpose(d),f=50*we[a]*we[c],f=f/(e[0][0]*e[0][0]+e[1][0]*e[1][0]);d[0]=numeric.mul(d[0],f);b=numeric.add(b,d[0])}return b}
function drawText(){Ifdebug||(context.clearRect(0,0,context.canvas.width,context.canvas.height),context.save(),context.fillStyle=backgroundcolor,context.fillRect(0,0,canvaswidth,canvasheight),context.restore());for(var a=0;a<bodyList.length;a++){var b=bodyList[a].GetWorldCenter(),c=bodyList[a].GetAngle();context.save();context.translate(b.x*drawScale,b.y*drawScale);context.rotate(c);var b=(maxfontsize-minfontsize)*we[a]+minfontsize,e=wo[a].visualLength(b,tagFont[a]);context.font="bold "+b+"px "+tagFont[a];
    context.fillStyle=tagColor[a];context.fillText(wo[a],-e/2,b/2*.9);context.restore()}if(hasselect.flag)if(ifaddconstrain){var d=constrainBody.length-1;if(constrainBody[d])for(a=0;a<constrainBody[d].length;a++)f=constrainBody[d][a],c=bodyList[f].GetAngle(),b=bodyList[f].GetWorldCenter(),e=bodywidth[f],f=bodyheight[f],context.save(),context.translate(b.x*drawScale,b.y*drawScale),context.rotate(c),context.strokeStyle="#009933",context.strokeRect(-e,-f,2*e,2*f),context.restore()}else{var f=selectedBody.GetID(),
    c=selectedBody.GetAngle(),b=selectedBody.GetWorldCenter(),e=bodywidth[f],f=bodyheight[f];context.save();context.translate(b.x*drawScale,b.y*drawScale);context.rotate(c);context.strokeStyle="#ff00ff";context.strokeRect(-e,-f,2*e,2*f);context.restore()}}function update(){mouseMoveAndRotate();centerAttract();forEachAttract();world.Step(1/60,10,10);world.DrawDebugData();drawText();world.ClearForces()}
function mouseMoveAndRotate(){isMouseMove&&(selectedBody.SetAngularVelocity(0),selectedBody.SetLinearVelocity(new b2Vec2(0,0)),selectedBody.SetAwake(!0),selectedBody.m_force.SetZero(),selectedBody.SetPosition(new b2Vec2(mouseX,mouseY)));if(isMouseRotate)if(firstrotate){var a=preselectBody.GetWorldCenter(),b=preselectBody.GetAngle();mrRadian=Math.atan2(mouseY-a.y,mouseX-a.x)-b;firstrotate=!1}else{selectedBody.SetAngularVelocity(0);selectedBody.SetLinearVelocity(new b2Vec2(0,0));selectedBody.SetAwake(!0);
    selectedBody.m_force.SetZero();var a=selectedBody.GetWorldCenter();selectedBody.SetAngle(Math.atan2(mouseY-a.y,mouseX-a.x)-mrRadian)}}
function centerAttract(){if(usecenter&&iternum<limit){for(var a=0;a<bodyList.length;a++)if(bodyList[a].GetAngle()>Math.PI/2+Math.PI/6&&bodyList[a].SetAngle(bodyList[a].GetAngle()-Math.PI),bodyList[a].GetAngle()<-(Math.PI/2+Math.PI/6)&&bodyList[a].SetAngle(bodyList[a].GetAngle()+Math.PI),ifattract[a])for(var b=0;b<planet.length;b++){var c=bodyList[a].GetWorldCenter(),e=planet[b].GetFixtureList().GetShape().GetRadius(),d=planet[b].GetWorldCenter(),f=new b2Vec2(0,0);f.Add(c);f.Subtract(d);c=f.Length();
    f.Normalize();c<=55E5*e&&(1>c?(bodyList[a].SetAngularVelocity(0),bodyList[a].SetLinearVelocity(new b2Vec2(0,0))):(f.NegativeSelf(),e=bodyList[a].GetMass(),f.Multiply(1*e*c*c/1.5),bodyList[a].ApplyForce(f,bodyList[a].GetWorldCenter())))}iternum++;100==iternum&&isFirstContrust&&(preserveConstrain(),isFirstContrust=!1)}}
function forEachAttract(){if(ifstart)if(iternum<limit){findNeighbor(!1,void 0);for(var a=0;a<bodyList.length;a++){var b=calattractF(a),b=new b2Vec2(2*-b[0],2*-b[1]);ifattract[a]?bodyList[a].ApplyForce(b,bodyList[a].GetWorldCenter()):(bodyList[a].SetAngularVelocity(0),bodyList[a].SetLinearVelocity(new b2Vec2(0,0)));if(isFirstContrust){var b=bodyList[a].GetLinearVelocity().x,c=bodyList[a].GetLinearVelocity().y;bodyList[a].SetLinearVelocity(new b2Vec2(.95*b,.95*c))}}}else if(ifedit&&bodyList[0].IsFixedRotation())if(shouldReWordle())ReWordle();
else{for(a=0;a<bodyList.length;a++)bodyList[a].SetAngularVelocity(0),bodyList[a].SetLinearVelocity(new b2Vec2(0,0)),limit=200;ifedit=!1}else for(a=0;a<bodyList.length;a++)bodyList[a].SetAngularVelocity(0),bodyList[a].SetLinearVelocity(new b2Vec2(0,0)),limit=200;for(a=0;a<bodyList.length;a++)prePosition[a]=bodyList[a].GetPosition();ifstart=!0}
function ReWordle(){for(var a=0,b=0,c=1E3,e=1E3,d=0;d<bodyList.length;d++)bodyList[d].GetWorldCenter().x>b&&(b=bodyList[d].GetWorldCenter().x),bodyList[d].GetWorldCenter().y>a&&(a=bodyList[d].GetWorldCenter().y),bodyList[d].GetWorldCenter().x<e&&(e=bodyList[d].GetWorldCenter().x),bodyList[d].GetWorldCenter().y<c&&(c=bodyList[d].GetWorldCenter().y);var f={x:(b-e)/2+e,y:(a-c)/2+c},a=Math.min((b-e)/2,(a-c)/2);console.log(a);b=[];for(d=0;d<bodyList.length;d++)if(e=bodyList[d].GetWorldCenter(),c=e.x-f.x,
        e=e.y-f.y,c=Math.sqrt(c*c+e*e),PreNeighbor[d]=wordsNeighbor[d],c>a*radiusRatio&&.5>we[d]){for(var e=!1,h=0;h<constrainBody.length;h++)1==constrainBody[h].indexOf(d)&&(e=!0);if(!e){drawnBody.remove(bodyList[d]);for(e=bodyList[d].GetFixtureList();e;e=e.m_next)e.SetSensor(!0);b.push({id:d,r:c})}}b.sort(sortNumber_forRewordle);neighberMove(f,b,Reflag);iternum=0;ifedit=!1;console.log("ReWordle Over");PreNeighbor=[]}
function neighberMove(a,b,c){if(c)for(c=0;c<bodyList.length;c++){b=!1;for(var e=bodyList[c].GetFixtureList();e;e=e.m_next)e.IsSensor()&&(b=!0);if(b){var d=bodyList[c].GetWorldCenter();drawnBody.remove(bodyList[c]);world.DestroyBody(bodyList[c]);var e=((d.x-a.x)*startPositionRatio+a.x)*drawScale,d=((d.y-a.y)*startPositionRatio+a.y)*drawScale,f=tagColor[c],h=bodyList[c].GetAngle(),g=tagFont[c];createBox(e,d,we[c],c,!1,f,h,g,!0)}}else for(var m=0;m<b.length;m++)c=b[m].id,d=bodyList[c].GetWorldCenter(),
    drawnBody.remove(bodyList[c]),world.DestroyBody(bodyList[c]),e=((d.x-a.x)*startPositionRatio+a.x)*drawScale,d=((d.y-a.y)*startPositionRatio+a.y)*drawScale,f=tagColor[c],h=bodyList[c].GetAngle(),g=tagFont[c],createBox(e,d,we[c],c,!1,f,h,g,!0)}
function PickPosition(a,b){for(var c=[],e=[],d=[],f=0;f<bodyList.length;f++)for(var h=bodyList[f].GetFixtureList();h;h=h.m_next)h.IsSensor()&&(e.push(f),d.push(wo[f]));e=RemoveSensor(PreNeighbor[b.GetID()],e);d=[];for(f=0;f<e.length;f++)d.push(wo[e[f]]);for(f=0;f<a.length;f++){d=a[f].x;h=a[f].y;b.SetPosition(new b2Vec2(d,h));for(var d=findNeighbor(!0,b.GetID()),h=[],g=0;g<d.length;g++)h.push(wo[d[g]]);c[f]=EvaluateScore(d,e)}c=c.indexOf(Math.max.apply(Math,c));d=a[c].x;h=a[c].y;b.SetPosition(new b2Vec2(d,
    h));drawnBody.push(b)}function RemoveSensor(a,b){for(var c=[],e=0;e<a.length;e++){for(var d=!1,f=0;f<b.length;f++)a[e]==b[f]&&(d=!0);d||c.push(a[e])}return c}function EvaluateScore(a,b){for(var c=0,e=0,d=0;e<a.length&&d<b.length;)a[e]!=b[d]?a[e]<b[d]?++e:++d:(c++,++e,++d);return c}
function shouldReWordle(){for(var a=0,b=0,c=1E3,e=1E3,d=0;d<bodyList.length;d++)bodyList[d].GetWorldCenter().x>b&&(b=bodyList[d].GetWorldCenter().x),bodyList[d].GetWorldCenter().y>a&&(a=bodyList[d].GetWorldCenter().y),bodyList[d].GetWorldCenter().x<e&&(e=bodyList[d].GetWorldCenter().x),bodyList[d].GetWorldCenter().y<c&&(c=bodyList[d].GetWorldCenter().y);for(var f=(b-e)/2+e,h=(a-c)/2+c,a=Math.min((b-e)/2,(a-c)/2),d=0;d<bodyList.length;d++)if(ifattract[d]&&(b=10*Math.PI/180,c=bodyList[d].GetAngle(),
    c<b&&c>-b||c>Math.PI/2-b&&c<Math.PI/2+b||c>-Math.PI/2-b&&c<-Math.PI/2+b)){var e=bodyList[d].GetWorldCenter(),g=e.x-f,m=e.y-h;if(Math.sqrt(g*g+m*m)<=.8*a)for(g=0;g<wordsNeighbor[d].length;g++){var m=bodyList[wordsNeighbor[d][g]].GetWorldCenter(),k=wordsNeighbor[d][g];if(ifattract[k]){var l=bodyList[k].GetAngle();if(l<b&&l>-b||l>Math.PI/2-b&&l<Math.PI/2+b||l>-Math.PI/2-b&&l<-Math.PI/2+b){var n=bodywidth[d],p=bodyheight[d],q=bodywidth[k],r=bodyheight[k];if(c>Math.PI/2-b&&c<Math.PI/2+b||c>-Math.PI/2-
    b&&c<-Math.PI/2+b)n=bodyheight[d],p=bodywidth[d];if(l>Math.PI/2-b&&l<Math.PI/2+b||l>-Math.PI/2-b&&l<-Math.PI/2+b)q=bodyheight[k],r=bodywidth[k];l=Math.abs(m.x-e.x)*drawScale-n-q;if(40<Math.abs(m.y-e.y)*drawScale-p-r){if(IfAnotherOK(!1,k,d)){console.log("xdiffer\u60c5\u51b5: "+wo[d]+" & "+wo[k]);if(preReWordleReason[0]==k&&preReWordleReason[1]==d||preReWordleReason[1]==k&&preReWordleReason[0]==d)return document.getElementById("canvasinfo").innerHTML="Maybe It is too far between words '"+wo[d]+"' and '"+
    wo[k]+"'.",$("#canvasinfo").fadeIn("fast"),$("#canvasinfo").delay(5E3).fadeOut("fast"),!1;preReWordleReason[0]=k;preReWordleReason[1]=d;return!0}}else if(70<l&&IfAnotherOK(!0,k,d)){console.log("xdiffer\u60c5\u51b5: "+wo[d]+" & "+wo[k]);if(preReWordleReason[0]==k&&preReWordleReason[1]==d||preReWordleReason[1]==k&&preReWordleReason[0]==d)return document.getElementById("canvasinfo").innerHTML="Maybe It is too far between words '"+wo[d]+"' and '"+wo[k]+"'.",$("#canvasinfo").fadeIn("fast"),$("#canvasinfo").delay(5E3).fadeOut("fast"),
    !1;preReWordleReason[0]=k;preReWordleReason[1]=d;return!0}}}}}return!1}
function IfAnotherOK(a,b,c){var e=bodyList[c].GetWorldCenter().x,d=bodyList[b].GetWorldCenter().x,f=bodyList[c].GetWorldCenter().y,h=bodyList[b].GetWorldCenter().y,g;e>d?(g=e,e=d):g=d;f>h?(d=f,f=h):d=h;if(a){var m=0,k=-10,l=1E3,n=-10;for(a=0;a<bodyList.length;a++)if(a!=c&&a!=b){var h=bodyList[a].GetWorldCenter().y,p=bodyList[a].GetWorldCenter().x;p>e&&p<g&&(h>d&&h<l&&(l=h,n=a),h<f&&h>m&&(m=h,k=a))}if(-10!=k&&-10!=n)return b=bodyheight[k],c=bodyheight[n],0!=bodyList[k].GetAngle()&&(b=bodywidth[k]),
0!=bodyList[n].GetAngle()&&(c=bodywidth[n]),35<Math.abs(m-l)*drawScale-b-c?!0:!1}else{m=0;k=-10;l=1E3;n=-10;for(a=0;a<bodyList.length;a++)a!=c&&a!=b&&(h=bodyList[a].GetWorldCenter().y,p=bodyList[a].GetWorldCenter().x,h>f&&h<d&&(p>g&&p<l&&(l=p,n=a),p<e&&p>m&&(m=p,k=a)));if(-10!=k&&-10!=n)return b=bodywidth[k],c=bodywidth[n],0!=bodyList[k].GetAngle()&&(b=bodyheight[k]),0!=bodyList[n].GetAngle()&&(c=bodyheight[n]),45<Math.abs(m-l)*drawScale-b-c?!0:!1}return!0}
function ifHorizontal(a){if(0==bodyList[a].GetAngle()){var b=bodyList[a].GetWorldCenter().x*drawScale,c=bodyList[a].GetWorldCenter().y*drawScale,e=bodywidth[a],d=bodywidth[a];a=[];for(var f=[],h=!1,g=0;g<bodyList.length;g++){var m=bodyList[g].GetWorldCenter().x*drawScale,k=bodyList[g].GetWorldCenter().y*drawScale;m<b&&k>c-10&&k<c+10&&a.push(g);m>b&&k>c-10&&k<c+10&&f.push(g)}if(void 0!=a[0]&&void 0!=f[0]&&(a.sort(sortNumber_forMove2),f.sort(sortNumber_forMove1),0==bodyList[a[0]].GetAngle()&&0==bodyList[f[0]].GetAngle())){var g=
    bodywidth[a[0]],l=bodywidth[f[0]],m=bodyList[a[0]].GetWorldCenter().x*drawScale,k=bodyList[f[0]].GetWorldCenter().x*drawScale,n=bodyList[a[0]].GetWorldCenter().y*drawScale,p=bodyList[f[0]].GetWorldCenter().y*drawScale,g=k-m-g-l;if(!(g>e)&&(b>(m+k)/2-e&&b<(m+k)/2+e&&c>(n+p)/2-d&&c<(n+p)/2+d&&(h=!0),h)){b=e/2-g/2+10;for(g=0;g<a.length;g++)m=bodyList[a[g]].GetWorldCenter().x,n=bodyList[a[g]].GetWorldCenter().y,bodyList[a[g]].SetPosition(new b2Vec2(m-b/drawScale,n));for(g=0;g<f.length;g++)k=bodyList[f[g]].GetWorldCenter().x,
    p=bodyList[f[g]].GetWorldCenter().y,bodyList[f[g]].SetPosition(new b2Vec2(k+b/drawScale,p))}}}}function sortNumber(a,b){return a-b}function sortNumber_forMove1(a,b){var c=bodyList[a].GetWorldCenter().x,e=bodyList[b].GetWorldCenter().x;return c-e}function sortNumber_forMove2(a,b){var c=bodyList[a].GetWorldCenter().x;return bodyList[b].GetWorldCenter().x-c}function sortNumber_forRewordle(a,b){return a.r-b.r}
function SaveEditData(){for(var a=[],b=[],c=0;c<bodyList.length;c++){var e={};e.x=bodyList[c].GetPosition().x;e.y=bodyList[c].GetPosition().y;a.push(e);b.push(bodyList[c].GetAngle())}a={word:wo,weight:we,position:a,angle:b,ifattract:ifattract,color:tagColor,font:tagFont,iffix:bodyList[0].IsFixedRotation(),constrain:constrainBody,iter:iternum};document.getElementById("myTextArea").innerHTML=JSON.stringify(a);a=document.createElement("input");b=document.getElementById("myTextArea").innerHTML||document.getElementById("myTextArea").value;
    a.setAttribute("value",b);document.body.appendChild(a);a.select();document.execCommand("copy");document.body.removeChild(a);alert("The edit data has been copied to the clipboard. You can paste it to the notepad and save it.")}
function LoadEditData(){var a=prompt("Please input edit data: ",""),a=eval("("+a+")"),b=!1;world||(world=new b2World(new b2Vec2(0,0),!0),createWall(),debugDraw(),b=!0);for(var c=0;c<bodyList.length;c++)world.DestroyBody(bodyList[c]);ifstart=!1;hasselect.flag=!1;bodyList=[];bodywidth=[];bodyheight=[];prePosition=[];drawnBody=[];preReWordleReason=[-1,-1];wo=a.word;we=a.weight;ifattract=a.ifattract;tagColor=a.color;tagFont=a.font;constrainBody=a.constrain;ReCreateObject_Load(a.position,a.angle,a.iffix,
    a.iter);b&&window.setInterval(update,1E3/60)}function ReCreateObject_Load(a,b,c,e){for(var d=0;d<wo.length;d++)ReCreateBody(a[d],b[d],c,d);iternum=e;ifstart=!1}
function ReCreateBody(a,b,c,e){fixDef.isSensor=!1;fixDef.density=1;fixDef.friction=.1;bodyDef.type=b2Body.b2_dynamicBody;fixDef.shape=new b2PolygonShape;var d=(maxfontsize-minfontsize)*we[e]+minfontsize,f=wo[e].visualLength(1.05*d,tagFont[e]);fixDef.shape.SetAsBox(f/drawScale/2,d/drawScale/2);bodyDef.position.Set(a.x,a.y);a=world.CreateBody(bodyDef);a.CreateFixture(fixDef);a.SetAngle(b);a.SetID(e);bodyList[e]=a;bodywidth[e]=f/2;bodyheight[e]=d/2;drawnBody.push(a);a.SetFixedRotation(c)}
function SaveNow(){for(var a=[],b=[],c=0;c<bodyList.length;c++){var e={};e.x=bodyList[c].GetPosition().x;e.y=bodyList[c].GetPosition().y;a.push(e);b.push(bodyList[c].GetAngle())}return{wordsPosition:a,wordsAngle:b,wordsIfatr:ifattract,wordsTagColor:tagColor,wordsIffix:bodyList[0].IsFixedRotation(),wordsiternum:iternum}}function ReLayout(){ifedit=hasselect.flag=!1;DestroyBody();ReSortWoandWe();createObject();limit=200;isFirstContrust=!0}
function DestroyBody(){for(var a=0;a<bodyList.length;a++)world.DestroyBody(bodyList[a]);ifstart=!1;bodyList=[];bodywidth=[];bodyheight=[];prePosition=[];drawnBody=[];ifattract=[];tagColor=[]}
function ReSortWoandWe(){for(var a=[].concat(wo),b=0;b<we.length;b++)for(var c=0;c<we.length-b-1;c++)if(we[c]<we[c+1]){var e=we[c],d=wo[c];we[c]=we[c+1];wo[c]=wo[c+1];we[c+1]=e;wo[c+1]=d}for(b=0;b<constrainBody.length;b++)for(c=0;c<constrainBody[b].length;c++)e=wo.indexOf(a[constrainBody[b][c]]),-1!=e&&(constrainBody[b][c]=e)}String.prototype.isInChinese=function(){return this.length!=this.replace(/[^\x00-\xff]/g,"**").length};
function getElementPosition(a){for(var b,c=0,e=0;"object"==typeof a&&"undefined"!=typeof a.tagName;)e+=a.offsetTop,c+=a.offsetLeft,b=a.tagName.toUpperCase(),"BODY"==b&&(a=0),"object"==typeof a&&"object"==typeof a.offsetParent&&(a=a.offsetParent);return{x:c,y:e}}$(document).ready(function(){$("#canvas").bind("contextmenu",function(a){return!1})});String.prototype.visualLength=function(a,b){var c=$("#textDomain");c.css("font-size",a+"px");c.css("font-family",b);c.text(this);return c[0].offsetWidth};
Array.prototype.remove=function(a){a=this.indexOf(a);-1<a&&this.splice(a,1)};